### ISSUE TITLE
Adjust Gedcom X to work with RDBMS

### ISSUE THREAD

**Issue by weitzhandler** [FamilySearch/gedcomx#278]
Hi,

Gedcom X, as an object supposed to be stored in XML or json, is object-oriented by nature.
This leads to an issue when trying to reflect the data into a Relational DataBase Management System DB, such as MSQL, MySql etc.

Perhaps, ANY type of data, field or complex-type, should have an ID field, to allow for efficient retrieval and storage to and from an RDBMS.

Besides, I tried to look up what IDs should be and what and how Identifiers should be used, whether there are any rules regarding this, and found this subject a bit unsolid.
Please clarify that, and the subject of my issue as well.

Thanks!

**Comment by ranbo** [comment]
There is often a tendency to want to "flatten" GedcomX data so that it can be modeled easily in relational database tables or pipe-delimited flat files. However, genealogical data is inherently complex, multi-valued and hierarchical in nature, so there is no good general-purpose way to map flat fields to and from GedcomX, unless you have very strong constraints on what the structure of your data is allowed to be.

A GedcomX person, for example, can have any number of names, each with multiple name forms (e.g., to support Korean hangul, Korean hanja, and Romanized forms of the same name), each of which can have a full text and multiple parts (each with a part type, such as two given name parts, a surname, and a suffix).

If you happen to know that nobody in your database will have more than one name, more than one name form, and only one part of each type, you might be able to get away with flattening the name out.

In the databases we use to represent GedcomX data, we don't try to store it flat (i.e., as key-value pairs or rows and columns of data). Rather, we have used several ways of storing the structured data with the structure intact. One way this can be done is with BLOBs in relational databases. Another way is to use NoSQL databases such as Cassandra to store the entire data structure (e.g., in compressed JSON or XML). Sometimes a few data items are duplicated into columns to allow for some querying. We have typically used a separate search system for serious searches, in which case we do 'flatten' data back down in a lossy way, which is fine for non-canonical searching.

The other option, of course, is to attempt to create a relational database that models the entire structure of GedcomX. However, there are so many nested lists, each of which would require additional tables and joins, that it is unlikely that this would be an efficient way to operate. Furthermore, it is uncommon to need to query against all of that complexity anyway, which is why it has worked well to bundle things up into BLOBs or other structures, and only put the things into columns that specifically need to be queried.

--Randy Wilson
  FamilySearch Information Architect

**Comment by weitzhandler** [comment]
Hi rando, and thanks for your great response.
I haven't actually thought of this idea of splitting up the data, that could actually work just great.
Because I can store the less essential parts of the data as XML (and it's searchable by the server!).
Great solution!

Another related question is, how do I optimize the date, which is something I would need to be able to lookup data with.

**Comment by ranbo** [comment]
GedcomX has specifications for a formal date, and there is a FormalDate utility class for parsing and creating strings according to the specification.

However, I think you're asking "how do I standardize a date?", i.e., how to come up with a FormalDate from an original date string. A lot of people have done a bunch of work to parse genealogical dates (in various languages) in order to figure out what they mean. Dallan Quass open-sourced his place and name standardizers. I'm not sure if there's an open source date parser around to point you at.

**Comment by weitzhandler** [comment]
Thanks.

I now realize that GitHub's mail response system makes no sense.
It should have omitted the original post and email addresses from your post above...

**Comment by weitzhandler** [comment]
Thanks a lot.

**Comment by fatso83** [comment]
Why is this an open issue? It's not really a bug that can be closed/fixed - more of a user question, it has been answered and is four years old, so more activity is not very likely to happen :smile: Just noting that closing old issues might be worth a look.

I can recommend integrating [StaleBot](https://github.com/apps/stale), btw.

**Comment by weitzhandler** [comment]
Lemme close this issue then.
