### ISSUE TITLE
PlaceDescription name specification vs example

### ISSUE THREAD

**Issue by eneufeld** [FamilySearch/gedcomx#283]
Hi, 
In the specification of the PlaceDescription (https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#place-description ) the names array is defined as a list of TextValues. 
So I would assume that in json it should look something like this: 
names:[{value: '"Pope's Creek'},{value: 'Westmoreland'},{value: 'Virginia'},{value: 'United States'}]
but in the examples (https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md#examples) it is simply a comma separated list if strings:
"names" : [ {
      "value" : "Pope's Creek, Westmoreland, Virginia, United States"
    } ],
in XML it is a plain string:
<name>Pope's Creek, Westmoreland, Virginia, United States</name>

Could you please clarify what is the correct way?
Thanks

**Comment by jralls** [comment]
The example is correct because "Pope's Creek, Westmoreland, Virginia, United States" is one place. It's a single string, not a list of strings. Although there are optional elements (jurisdiction, type) for creating a hierarchical place structure, there's no requirement to do so. FamilySearch appears to have implemented a hierarchy for their [Place Authority](https://familysearch.org/developers/docs/api/resources#places).
If the place has multiple names, e.g. "Pope's Creek, Northumberland, Virginia, United States" (assuming that Pope's Creek existed in 1653) then there would be multiple values in "names".

**Comment by stoicflame** [comment]
@jralls is correct; the multiple name values are just values of the place which are expected to include the hierarchy. The reason there are multiple values is for internationalization; you can provide multiple names based off the `lang`.

If you'd like to explicitly declare the jurisdiction hierarchy, you can provide multiple instances of `PlaceDescription`, each pointing to the description of its jurisdiction using the `jurisdiction` property.

The specs and examples can be clarified; I'll leave this issue open until we get those applied. But here's kinda what the examples should look like:

```json
{
  "places" : [ {
    "names" : [
      {
        "lang" : "en"
        "value" : "Pope's Creek, Westmoreland, Virginia, United States"
      } ,
      {
        "lang" : "zh"
        "value" : "教皇的小河，威斯特摩兰，弗吉尼亚州，美国"
      } 
    ]
  } ]
}
```

```xml
<gedcomx>
  <place>
    <name lang="en">Pope's Creek, Westmoreland, Virginia, United States</name>
    <name lang="zh">教皇的小河，威斯特摩兰，弗吉尼亚州，美国</name>
  </place>
</gedcomx>
```

**Comment by eneufeld** [comment]
Hi, 
thank you for the clarification.
