### ISSUE TITLE
jurisdiction of PlaceDescription

### ISSUE THREAD

**Issue by eneufeld** [FamilySearch/gedcomx#288]
The jurisdiction field of the PlaceDescription has the data type URI but must resolve to a PlaceDescription. Why is it not defined as a PlaceReference?

**Comment by stoicflame** [comment]
So the `PlaceReference` was really designed to model "conclusion-type" data, so it includes a place for "original" text, and we didn't think that the concept of "original" text applied in the context of a `PlaceDescription`. So we just left a reference.

Thoughts?

**Comment by eneufeld** [comment]
As far as I can see, the original field is optional, so it could be omitted by the user if a real reference is there. On the other hand a user could use the "original" field to create a temporary "link" without creating the PlaceDescription object yet.
The main advantage of a PlaceReference would be that it would make the referenced type very clear.

**Comment by stoicflame** [comment]
Yes, I acknowledge your good points.

The trade-off with using `PlaceReference` is a some confusion. We'd have to answer questions like:

* What if there's a reference _and_ original text?
* What if the original text conflicts with the names of the `PlaceDescription` being referenced? Which names get priority?

So rather than have to deal with those questions, we just decided to make it a simple URI reference instead of a full `PlaceReference`.

**Comment by eneufeld** [comment]
I see the argument. 
I think that you have to answer those questions always when you use a PlaceReference, as for example in a fact.
But I understand that there is a slight difference between the case of the jurisdiction and the case of a place in a fact.

**Comment by stoicflame** [comment]
I also acknowledge the value in your argument, but at this point I don't think the value is worth the cost of changing it.
