### ISSUE TITLE
Is the spec missing root element properties?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx#293]
[`Gedcomx.java`](https://github.com/FamilySearch/gedcomx-java/blob/7f5cc7964b352042f2041a599d3e94c5ba694ddc/gedcomx-model/src/main/java/org/gedcomx/Gedcomx.java#L88-L90) lists three properties that are not mentioned in the Conceptual Model, JSON Serialization Format, or XML Serialization Format: `lang`, `description`, `profile`. Are they supposed to be included in the spec?

**Comment by stoicflame** [comment]
The `lang` property is [implied in section 1.4](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#14-internationalization-considerations).

The `Gedcomx` data type isn't defined in the conceptual model because its use is as a container for serialization purposes. So:

* The `lang` property is defined in the XML, JSON specs (see section 4.3 of each spec).
* The `description` property is defined in the XML, JSON specs (see section 4.3 of each spec).
* The `profile` property was added as an experiment in the Java library, but it's not getting used, so I'll remove it for now.

**Comment by justincy** [comment]
Thanks. I remember looking at section 4.3 in the JSON spec. Not sure how I missed `lang` and `description` in there.
