### ISSUE TITLE
Add Tribe as a known fact type

### ISSUE THREAD

**Issue by Asparagirl** [FamilySearch/gedcomx#296]
Inspired by #295. This could potentially mean anything from "Cohen" to "Cherokee", depending on the family background, and because tribal status can carry religious or legal implications, this really should be documented.

**Comment by stoicflame** [comment]
:+1:

**Comment by Amgine0** [comment]
[Métis](https://en.wikipedia.org/wiki/M%C3%A9tis "They are descendants of specific mixed First Nations and European ancestry who self-identify as Métis, *and* are accepted into their current community."). Or, for that matter, Dixson sept clan Keith.

Again, bad data. Blood quantum, 'status' versus 'non-status', etc. "I have an indian princess in my heritage" may be a reasonable family legend, but how do you prove it? Every legal venue may have different tests, and how would normalizing across milieu work? (As someone who has been working on this *exact* issue for more than 2 decades…)

The point is we should not track bad data. Full-stop. Because this encourages amateur genealogists to track bad data.

**Comment by jralls** [comment]
Genealogists don't "track data". We study records to extract evidence, and that evidence often includes statements about race, ethnicity and tribe. Discarding it because we now know it to be scientifically invalid would be silly, especially in cases where those distinctions might be the only evidence that there are e.g. two John Joneses in a community.

Suggesting that one not extract the race field in a census would get you laughed out of any group of professional genealogists; ignoring that evidence would get your paper rejected by any serious journal.

**Comment by Amgine0** [comment]
I keep data in my ged. Not paper.

Keeping the race field in the source is where it should be. It is *not* a fact, so of course it should not be tracked as a person fact. But maybe you think otherwise.

**Comment by jralls** [comment]
By "paper" I meant an article submitted for publication in a scholarly journal.

Please see my reply to you in #295 regarding terms.

**Comment by Asparagirl** [comment]
But plenty of people have a perfectly valid tribal status, whether it's nothing that someone's Hebrew name is "Joseph ben Yitzhak haLevi" on a tombstone (denotes the tribe of Levi, which still has modern religious implications) or Jane Doe who is legally on the tribal rolls for a Native American tribe (which has legal implications) and really is the fabled "Indian princess".

Sure, some genealogists may stick inaccurate or wishful information in a "Tribe" field but some of us won't. Why shouldn't we be able to document tribal status?

**Comment by Asparagirl** [comment]
True story: I just passed a parked car that had a bumper sticker saying "I am proud to be Tlingit". Why should that fact be recorded on a car but verboten in a GEDCOM?

**Comment by stoicflame** [comment]
Okay, so activity seems to have settled on this thread. I _think_ that the generally-accepted conclusion is that `Tribe` should be added to the spec as a known fact type because it meets the [Criteria for New Fact Types](https://github.com/FamilySearch/gedcomx/blob/master/specifications/fact-types-specification.md#3-criteria-for-new-fact-types):

* It clearly demonstrates a useful purpose within the context of genealogical research because the term is used in historical genealogical and legal documents.
* It does not overlap the definition of any existing fact type.
* It demonstrates reasonable applicability; the data on a historical document needs to be captured.
* It demonstrates reasonable applicability across differing geographic, cultural, and regional contexts.

@Amgine0's points about the complexities of accurately defining and determining `Tribe` should be taken into consideration by developers when making choices about how their particular genealogical application should be implemented. However, the intention of the spec is to facilitate the sharing of genealogical data, including data that has been captured from historical documents which declare `Tribe`. How applications _handle_ that data is beyond the scope of the spec.

I have submitted #298 for your consideration. I'll give a few more days after any further discussion settles before I merge.
